# Generated by Django 4.2.10 on 2026-02-02 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📦', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('expedie', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('ville_livraison', models.CharField(max_length=100)),
                ('code_postal_livraison', models.CharField(max_length=20)),
                ('pays_livraison', models.CharField(default='France', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_commande',),
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_admin', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_inscription',),
                'indexes': [models.Index(fields=['email'], name='store_utili_email_bf4d33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/%Y/%m/%d/')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nouveau', models.BooleanField(default=False)),
                ('en_promotion', models.BooleanField(default=False)),
                ('tailles', models.JSONField(blank=True, default=list)),
                ('couleurs', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='store.categorie')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='store.utilisateur')),
            ],
            options={
                'ordering': ('-date_modification',),
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taille', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='store.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='store.produit')),
            ],
            options={
                'ordering': ('commande',),
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='store.utilisateur'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taille', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='store.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_panier', to='store.produit')),
            ],
            options={
                'ordering': ('-date_ajout',),
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie', 'prix'], name='store_produ_categor_dd7145_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['en_promotion'], name='store_produ_en_prom_622df0_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nouveau'], name='store_produ_nouveau_ad8da1_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['utilisateur', 'date_commande'], name='store_comma_utilisa_5132db_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='store_comma_statut_9febc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('panier', 'produit', 'taille', 'couleur')},
        ),
    ]
