# Generated by Django 4.2.10 on 2026-07-06 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ('-date_inscription',),
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('commande', 'Commande'), ('promotion', 'Promotion'), ('info', 'Information')], default='info', max_length=20)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.utilisateur')),
            ],
            options={
                'ordering': ('-date_creation',),
                'indexes': [models.Index(fields=['utilisateur', 'lu'], name='store_notif_utilisa_fd95a9_idx')],
            },
        ),
    ]
