# Generated by Django 4.2.10 on 2026-07-06 02:00

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_abonnenewsletter_utilisateur_fcm_token_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Money'), ('wave', 'Wave'), ('moov', 'Moov Money'), ('autre', 'Autre')], default='orange', max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('nom_beneficiaire', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Numéro de paiement',
                'verbose_name_plural': 'Numéros de paiement',
                'ordering': ('-actif', 'operateur'),
            },
        ),
        migrations.CreateModel(
            name='ParametresBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=1500, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres boutique',
                'verbose_name_plural': 'Paramètres boutique',
            },
        ),
        migrations.AddField(
            model_name='abonnenewsletter',
            name='token_desinscription',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('mobile_money_direct', 'Mobile Money direct'), ('cinetpay', 'CinetPay (carte + Mobile Money)')], default='livraison', max_length=30),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_livraison',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
