# Generated by Django 4.2.10 on 2026-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_numeropaiement_parametresboutique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='code_postal_livraison',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pays_livraison',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
    ]
