# Generated by Django 4.2.10 on 2026-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_commande_latitude_commande_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
    ]
