# Generated by Django 4.2.10 on 2026-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_utilisateur_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Reçue'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
